"use client";
import { Provider } from "react-redux";
import Navbar from "@/components/Navbar";
import "./globals.css";
import Footer from "@/components/Footer";
import { store } from "@/store";
import { Roboto } from "next/font/google";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className={`w-full h-screen bg-white ${roboto.className}`}>
          <Provider store={store}>
            <Navbar />
            {children}
            <Footer />
          </Provider>
        </main>
      </body>
    </html>
  );
}
